### ISSUE TITLE
Quickstart and all other reference architectures do not set cluster storage to delete on destroy

### ISSUE THREAD

**Issue by timroster** [IBM/automation-ibmcloud-infra-openshift#15]
For the Quickstart reference architecture which will most probably be used for short term and non-production data, it would be better to have `cluster_force_delete_storage` set to `true` so that storage is deprovisioned during cluster destroy. 

Other reference architectures may be better keeping with the module default of `false`.

**Comment by rich-ehrhardt** [comment]
There is a purge_volumes variable that has been added. Setting this true will delete any volumes created. This has been done in the github actions as well.
